version: '3.7'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
  server:
    depends_on:
      - mongo
    build: .
    ports:
      - 2137:2137

volumes:
  mongodb_data_container:
